server:
  port: 8090
  servlet:
    context-path: /template/api

spring:
  profiles:
    active: dev
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  servlet:
    multipart:
      location: /Users/sunjy/Desktop/Repo
      max-file-size: 10MB
      max-request-size: 10MB
  freemarker:
    template-loader-path: classpath:/templates/
    suffix: .ftl