spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_template?useUnicode=true&characterEncoding=UTF8&useSSL=true&serverTimezone=America/Los_Angeles
    username: root
    password: root1234
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 5
      minimum-idle: 2
      idle-timeout: 300000
      max-lifetime: 1800000
      auto-commit: true
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    open-in-view: true
